name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.preset }}
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - preset: win x64 Release
            build_preset: x64 Release
          - preset: win x64 Debug
            build_preset: x64 Debug
          - preset: win x86 Release
            build_preset: x86 Release
          - preset: win x86 Debug
            build_preset: x86 Debug

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset "${{ matrix.preset }}"

    - name: Build
      run: cmake --build --preset "${{ matrix.build_preset }}"
